apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: node-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:4.2.8
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: volume-01
              mountPath: /data
      volumes:
        - name: volume-01
          persistentVolumeClaim:
            claimName: pv-claim-01
