apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: node-mongo
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: app
